services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teama
      MYSQL_USER: teama
      MYSQL_PASSWORD: teama
    volumes:
      - ./container/data/mariadb/data:/var/lib/mysql:cached
    labels:
      org.springframework.boot.service-connection: mariadb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./container/data/nginx/www/html:/var/www/html
      - ./container/data/nginx/etc/default.conf:/etc/nginx/default.conf


